### ISSUE TITLE
[V&V Plan] Team30 Review: Tests for Functional Requirements - NB-3, EB-3, BB-5

### ISSUE THREAD

**Issue by edwin-do** [JonCels/chess-connect#125]
- Since for each game mode (normal, beginner and engine) exists a case where the game will resign due to one player holding down the DRAW button and the game must be in active state for this to occur, it could be possible to condense this into one test case under the tests for Game Active State (GA)

**Comment by vankraa** [comment]
It's easier to keep them separate to allow them to be organized based on differing game states. Otherwise most tests would be categorized under Game Active
