### ISSUE TITLE
[DesDoc] Team29 Review: MIS Module Exception Conditions

### ISSUE THREAD

**Issue by Kabishan** [JonCels/chess-connect#148]
Great work on the MIS, MG and System Design documents. 🎉 

For the MIS document, I believe it would be a great addition to the Final Revision document to include the conditions required for each of the exceptions to be thrown.

For example, for the **Piece Identification Module**, the *SensorOffline* exception could be thrown when the information retrieved from the sensor is **null** or when the information remains **null** for a pre-defined duration, such as *five* seconds.

Otherwise, a solid effort.

**Comment by Kabishan** [comment]
@CSchank

**Comment by jtgc1** [comment]
Issue is resolved by adding an exceptions section to each module. Thanks!
