### ISSUE TITLE
[DesDoc] Team29 Review: MIS Enum Modules

### ISSUE THREAD

**Issue by albertzevanescent** [JonCels/chess-connect#150]
@CSchank

For specifying enumerations, I recommend following the example from SE2AA4 from [https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Assignments/PreviousYears/2020/A2-ChemReacts/A2.pdf](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/Assignments/PreviousYears/2020/A2-ChemReacts/A2.pdf).
Something like gameMode referenced by the Chess Board module should be defined in its own module instead of as part of the Arduino Controller module.

**Comment by jtgc1** [comment]
Gamemode is just a variable modified by the modules. No need for separate module.
