### ISSUE TITLE
[DesDoc] Team29 Review: System Design Document - Reflection

### ISSUE THREAD

**Issue by almen-ng** [JonCels/chess-connect#152]
The TA for this capstone group is: @CSchank

With the Reflection, there are two questions that need to be answered:

- What are the limitations of your solution? Put another way, given unlimited resources, what could you do to make the project better? (LO_ProbSolutions)
- Give a brief overview of other design solutions you considered. What are the benefits and tradeoffs of those other designs compared with the chosen design? From all the potential options, why did you select documented design?

It seems like only one question (the brief overview of design solutions) was answered, but the limitations question was not. Some limitations that can be addressed can include having to always be connected to the internet.

**Comment by aujlaa4** [comment]
Thanks for the feedback. I have added the limitations section to the document.
