### ISSUE TITLE
[DesDoc] Team29 Review: System Design Document - Abbreviations & Acronyms

### ISSUE THREAD

**Issue by almen-ng** [JonCels/chess-connect#153]
The TA for this capstone group is: @CSchank

For the Abbreviations and Acronyms section, there seems to be duplicate headings as well as missing abbreviations/acronyms, for example, AI, LED, LCD, GA, NB, BB, etc. A quick solution to this would be to reference the SRS in this section as well as adding any additional abbreviations and acronyms that aren't included in the similar heading on the SRS.

**Comment by aujlaa4** [comment]
Thanks. I made your suggested change
