### ISSUE TITLE
[DesDoc] Team29 Review: MG - Anticipated Changes

### ISSUE THREAD

**Issue by davidwyao** [JonCels/chess-connect#154]
@CSchank

Neat project idea with lots of potential for creative hardware solutions.

Some of your anticipated and unlikely changes could do with some clarification. For AC9, what different user actions are you thinking about? For UC1, does this mean online PvP is supported or not supported? What is the difference between UC3 and UC5?

**Comment by jtgc1** [comment]
Great advice, thanks. Implemented
