### ISSUE TITLE
[DesDoc] Team29 Review: MG - Use Hierarchy Between Modules

### ISSUE THREAD

**Issue by JAYapeter** [JonCels/chess-connect#155]
Great work on the three Design Documents! 

Looking at the Use Hierarchy between Modules in the Module Guide, I noticed that there's a separation in the hierarchy between the web app and the physical board. It might be beneficial to explicitly show which module allows those two parts of the system to work with each other, or add that module if it does not exist yet.

@CSchank

**Comment by jtgc1** [comment]
Thanks for the advice, I think these connections are implicit within the modules contained in each level. Thanks
