### ISSUE TITLE
Team 2 Review: Verifiable Requirements

### ISSUE THREAD

**Issue by yuvrajrr** [JonCels/chess-connect#68]
The FR and NFRs are great, however there are certain requirements that seemed to be difficult to verify using this SRS. In the Speed and Latency requirements for example, the requirements mention the timing as being "small" and although you mention that "small" will be determined after the VnV plan, I believe the SRS should be a stand alone document in which the requirements should be verifiable and could be looked back at to check the progress or general direction in certain aspects of the project.

**Comment by ghost** [comment]
Leaving as-is. Though SRS could be a standalone document with these changes, the focus of the SRS is not verifiability. Verifiability is instead specified in more detail in the VnV Plan
