### ISSUE TITLE
Team 1 Reviews Team 4's HA

### ISSUE THREAD

**Issue by baenseul** [JonCels/chess-connect#99]
Hi Team4!

According to Dr. Smith's md file, it seems like we (team 1) will be reviewing your Hazard Analysis. Do you mind changing your label to reflect our team# please?

Thank you.

![Capture](https://user-images.githubusercontent.com/113210642/197321779-27de3446-deef-4695-95d7-6e7595531815.PNG)

@JonHaiMcMaster

**Comment by vankraa** [comment]
Thanks for letting us know about that!
